version: "3.9"
services:
  push:
    image: 117503445/push
    container_name: push
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.yml:/root/config/application.yml
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: --requirepass "MY_PASSWORD" --appendonly yes # CHANGE PASSWORD !!!