version: "3.9"
services:
  push:
    image: 117503445/push
    container_name: push
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./application.yml:/root/config/application.yml
  redis:
    image: redis
    restart: unless-stopped
    command: --requirepass "MY_PASSWORD" --appendonly yes # CHANGE PASSWORD !!!